Update devsecops.yml

diff --git a/.github/workflows/devsecops.yml b/.github/workflows/devsecops.yml
--- a/.github/workflows/devsecops.yml
+++ b/.github/workflows/devsecops.yml
@@ -17,7 +17,7 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
-      # 1. SAST - Semgrep (Phát hiện lỗi là dừng)
+      # 1. SAST - Semgrep
       - name: SAST Scan (Semgrep)
         run: |
           pip install semgrep
@@ -30,7 +30,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           
-      # 3. SCA - Snyk (Tạo policy bỏ qua Werkzeug và PyJWT)
+      # 3. SCA - Snyk (ignore Werkzeug, PyJWT)
       - name: SCA Scan (Snyk)
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
@@ -38,7 +38,6 @@ jobs:
           npm install -g snyk
           snyk auth $SNYK_TOKEN
           
-          # TẠO FILE CHÍNH SÁCH .snyk TRỰC TIẾP ĐỂ BỎ QUA 2 LỖ HỔNG
           cat <<EOF > .snyk
           version: v1.25.0
           ignore:
@@ -51,22 +50,18 @@ jobs:
                   reason: 'Unable to update pyjwt without breaking changes'
                   expires: '2026-12-31T00:00:00.000Z'
           EOF
-          
-          # Chạy quét (Snyk sẽ đọc file .snyk ở trên và tự động pass)
           snyk test --file=requirements.txt --command=python3 --skip-unresolved --severity-threshold=high
-      # 4. Khởi động ứng dụng (Mồi cho DAST)
-      - name: Start App for DAST
+          
+      # 4. Start app for DAST
+      - name: Start app
         run: |
           nohup python app.py > app.log 2>&1 &
           sleep 10
-          # Nếu curl thất bại, in toàn bộ nội dung file log ra màn hình trước khi dừng pipeline
-          curl --silent --fail http://localhost:5000/ || (echo "=== APP FAILED TO START. READING APP.LOG ===" && cat app.log && exit 1)
+          curl --silent --fail http://localhost:5000/ || (echo "APP FAILED TO START. READING APP.LOG" && cat app.log && exit 1)
 
-      # 5. DAST - OWASP ZAP (Quét thực tế, có lỗi là dừng)
-      # Sửa v0.7.0 thành v0.15.0
+      # 5. DAST - OWASP ZAP
       - name: ZAP Baseline Scan
         uses: zaproxy/action-baseline@v0.15.0
         with:
-          target: 'http://localhost:5000' # (Hoặc link bạn đang cấu hình)
-          # Thêm dòng này để chỉ định cứng Docker Image nguồn cho chắc chắn
+          target: 'http://localhost:5000'
           docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
